services:
  iaso:
    environment:
      SWISSTPH_IMPACT_DB_NAME:
      SWISSTPH_IMPACT_DB_USERNAME:
      SWISSTPH_IMPACT_DB_PASSWORD:
      SWISSTPH_IMPACT_DB_HOST:
      SWISSTPH_IMPACT_DB_PORT:
      SWISSTPH_CMR_IMPACT_DB_NAME:
      SWISSTPH_CMR_IMPACT_DB_USERNAME:
      SWISSTPH_CMR_IMPACT_DB_PASSWORD:
      SWISSTPH_CMR_IMPACT_DB_HOST:
      SWISSTPH_CMR_IMPACT_DB_PORT:
      IDM_IMPACT_DB_NAME:
      IDM_IMPACT_DB_USERNAME:
      IDM_IMPACT_DB_PASSWORD:
      IDM_IMPACT_DB_HOST:
      IDM_IMPACT_DB_PORT:
