# Generated by Django 4.2.18 on 2025-02-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="cost_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
