# Generated by Django 4.2.19 on 2025-02-19 07:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0338_metrictype_metricvalue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("snt_malaria", "0002_intervention_cost_per_unit"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InterventionFamily",
            new_name="InterventionCategory",
        ),
        migrations.RenameField(
            model_name="intervention",
            old_name="intervention_family",
            new_name="intervention_category",
        ),
        migrations.AlterUniqueTogether(
            name="intervention",
            unique_together={("intervention_category", "name")},
        ),
    ]
