# Generated by Django 4.2.19 on 2025-02-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0003_rename_interventionfamily_interventioncategory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interventioncategory",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Intervention categories",
            },
        ),
        migrations.AlterField(
            model_name="interventionassignment",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervention_assignments",
                to="snt_malaria.scenario",
            ),
        ),
    ]
