# Generated by Django 4.2.20 on 2025-03-25 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0004_alter_interventioncategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scenario",
            options={"ordering": ["-updated_at"]},
        ),
    ]
