# Generated by Django 4.2.20 on 2025-06-03 08:01

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snt_malaria", "0005_alter_scenario_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterventionMix",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=255)),
                ("interventions", models.ManyToManyField(to="snt_malaria.intervention")),
                ("scenario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="intervention_mixes", to="snt_malaria.scenario")),
            ],
        ),
    ]
