# Generated by Django 4.2.20 on 2025-06-03 12:44

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0338_metrictype_metricvalue"),
        ("snt_malaria", "0006_interventionmix"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="interventionassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="intervention_mix",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="snt_malaria.interventionmix"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interventionassignment",
            unique_together={("scenario", "org_unit", "intervention_mix")},
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="intervention",
        ),
    ]
