# Generated by Django 4.2.23 on 2025-08-12 07:25

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0006_interventionmix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interventionassignment",
            name="deleted_at",
        ),
        migrations.AlterField(
            model_name="interventionassignment",
            name="intervention",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="snt_malaria.intervention"
            ),
        ),
        migrations.DeleteModel(
            name="InterventionMix",
        ),
    ]
