# Generated by Django 4.2.20 on 2025-06-04 09:35

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0327_merge_20250424_0829"),
        ("snt_malaria", "0007_alter_interventionassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interventionmix",
            options={"ordering": ["name"], "verbose_name_plural": "Intervention mixes"},
        ),
        migrations.AddField(
            model_name="interventionmix",
            name="account",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.account"),
        ),
        migrations.AlterUniqueTogether(
            name="interventionmix",
            unique_together={("account", "name")},
        ),
    ]
