# Generated by Django 4.2.23 on 2025-08-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0007_remove_interventionassignment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionassignment',
            name='intervention',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='snt_malaria.intervention'),
            preserve_default=False,
        ),
    ]
