# Generated by Django 4.2.24 on 2025-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0008_alter_interventionassignment_intervention"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="cost_unit",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
