# Generated by Django 4.2.20 on 2025-06-06 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0008_alter_interventionmix_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="interventionmix",
            unique_together={("name",)},
        ),
    ]
