# Generated by Django 4.2.24 on 2025-09-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0009_intervention_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionCostLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
