# Generated by Django 4.2.24 on 2025-09-18 15:20

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0343_importgpkg_default_valid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("snt_malaria", "0009_intervention_cost_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="intervention",
            old_name="cost_unit",
            new_name="unit_type",
        ),
        migrations.RemoveField(
            model_name="intervention",
            name="cost_per_unit",
        ),
        migrations.RemoveField(
            model_name="intervention",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="intervention",
            name="unit_cost",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name="CostBreakdownLineCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.account")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_breakdown_line_category_created_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_breakdown_line_category_updated_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CostBreakdownLine",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(max_length=255)),
                ("cost", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="snt_malaria.costbreakdownlinecategory"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_breakdown_line_created_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="snt_malaria.intervention"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_breakdown_line_updated_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
