# Generated by Django 4.2.23 on 2025-07-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0009_alter_interventionmix_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interventionmix',
            unique_together={('name', 'scenario')},
        ),
    ]
