# Generated by Django 4.2.25 on 2025-10-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0010_rename_cost_unit_intervention_unit_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="code",
            field=models.CharField(default="default", max_length=255),
            preserve_default=False,
        ),
    ]
