# Generated by Django 4.2.24 on 2025-09-11 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("snt_malaria", "0010_interventioncostline"),
    ]

    operations = [
        migrations.AddField(
            model_name="interventioncostline",
            name="cost",
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interventioncostline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interventioncostline",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interventioncostline",
            name="intervention",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="snt_malaria.intervention"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interventioncostline",
            name="name",
            field=models.TextField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interventioncostline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="InterventionCostCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interventioncostline",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="snt_malaria.interventioncostcategory"
            ),
            preserve_default=False,
        ),
    ]
