# Generated by Django 4.2.25 on 2025-10-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0010_rename_cost_unit_intervention_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='end_year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='start_year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
