# Generated by Django 4.2.23 on 2025-07-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0338_metrictype_metricvalue"),
        ("snt_malaria", "0010_alter_interventionmix_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="interventionassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="intervention",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="snt_malaria.intervention"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interventionassignment",
            unique_together={("scenario", "org_unit", "intervention")},
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="intervention_mix",
        ),
        migrations.DeleteModel(
            name="InterventionMix",
        ),
    ]
