# Generated by Django 4.2.25 on 2025-10-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0011_alter_intervention_unit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
