# Generated by Django 4.2.23 on 2025-07-22 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0011_alter_interventionassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interventionassignment",
            name="deleted_at",
        ),
    ]
