# Generated by Django 4.2.25 on 2025-10-14 13:07

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0348_alter_assignment_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("snt_malaria", "0011_scenario_end_year_scenario_start_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="code",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BudgetSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("local_currency", models.CharField(max_length=3)),
                ("exchange_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inflation_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.account")),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.TextField()),
                ("cost_input", models.JSONField()),
                ("assumption", models.JSONField()),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_created_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("scenario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="snt_malaria.scenario")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_edited_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
