# Generated by Django 4.2.24 on 2025-09-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0343_importgpkg_default_valid"),
        ("snt_malaria", "0011_interventioncostline_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interventioncostcategory",
            name="account",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.account"),
            preserve_default=False,
        ),
    ]
