# Generated by Django 4.2.25 on 2025-10-20 12:57

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0348_alter_assignment_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("snt_malaria", "0012_scenario_end_year_scenario_start_year_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="intervention",
            unique_together={("intervention_category", "name")},
        ),
        migrations.AddField(
            model_name="intervention",
            name="code",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interventioncostbreakdownline",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("PER_ITN", "per ITN"),
                    ("PER_SP", "per SP"),
                    ("PER_CHILD", "per child"),
                    ("PER_DOSE", "per dose"),
                    ("PER_SPAQ_3_11_MONTHS", "per SPAQ pack 3-11 month olds"),
                    ("PER_SPAQ_12_59_MONTHS", "per SPAQ pack 12-59 month olds"),
                    ("PER_SPAQ_5_10_YEARS", "per SPAQ pack 5-10 years olds"),
                    ("PER_RDT_KIT", "per RDT kit"),
                    ("PER_AL", "per AL"),
                    ("PER_60MG_POWDER", "per 60mg powder"),
                    ("PER_RAS", "per RAS"),
                    ("PER_BALE", "per bale"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="interventioncostbreakdownline",
            name="year",
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="intervention",
            unique_together={("intervention_category", "name"), ("intervention_category", "code")},
        ),
        migrations.CreateModel(
            name="BudgetSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("local_currency", models.CharField(max_length=3)),
                ("exchange_rate", models.DecimalField(decimal_places=10, max_digits=20)),
                ("inflation_rate", models.DecimalField(decimal_places=10, max_digits=20)),
                ("account", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="iaso.account")),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.TextField()),
                ("cost_input", models.JSONField()),
                ("assumptions", models.JSONField()),
                ("results", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_created_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("scenario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="snt_malaria.scenario")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_edited_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RemoveField(
            model_name="intervention",
            name="unit_cost",
        ),
        migrations.RemoveField(
            model_name="intervention",
            name="unit_type",
        ),
    ]
