# Generated by Django 4.2.24 on 2025-09-12 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snt_malaria', '0012_interventioncostcategory_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterventionCostLine',
            new_name='InterventionCost',
        ),
    ]
