# Generated by Django 4.2.25 on 2025-10-20 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0014_update_intervention_names_and_set_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="intervention",
            unique_together={("intervention_category", "name")},
        ),
    ]
