# Generated by Django 4.2.27 on 2025-12-15 14:24

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0014_update_intervention_names_and_set_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetAssumptions",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("divisor", models.DecimalField(decimal_places=2, max_digits=3)),
                ("bale_size", models.IntegerField()),
                ("buffer_mult", models.DecimalField(decimal_places=2, max_digits=3)),
                ("coverage", models.DecimalField(decimal_places=2, max_digits=3)),
                ("doses_per_pw", models.IntegerField()),
                ("age_string", models.CharField()),
                ("pop_prop_3_11", models.DecimalField(decimal_places=2, max_digits=3)),
                ("pop_prop_12_59", models.DecimalField(decimal_places=2, max_digits=3)),
                ("monthly_rounds", models.IntegerField()),
                ("touchpoints", models.IntegerField()),
                ("tablet_factor", models.DecimalField(decimal_places=2, max_digits=3)),
                ("doses_per_child", models.IntegerField()),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention",
                        to="snt_malaria.intervention",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scenario", to="snt_malaria.scenario"
                    ),
                ),
            ],
            options={
                "unique_together": {("scenario", "intervention")},
            },
        ),
    ]
