# Generated by Django 4.2.27 on 2025-12-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0014_update_intervention_names_and_set_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAssumptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('bale_size', models.IntegerField()),
                ('buffer_mult', models.DecimalField(decimal_places=2, max_digits=3)),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('doses_per_pw', models.IntegerField()),
                ('age_string', models.CharField()),
                ('pop_prop_3_11', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pop_prop_12_59', models.DecimalField(decimal_places=10, max_digits=20)),
                ('monthly_rounds', models.IntegerField()),
                ('touchpoints', models.DecimalField(decimal_places=10, max_digits=20)),
                ('tablet_factor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('doses_per_child', models.IntegerField()),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='snt_malaria.intervention')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario', to='snt_malaria.scenario')),
            ],
            options={
                'unique_together': {('scenario', 'intervention')},
            },
        ),
    ]
