# Generated by Django 4.2.27 on 2025-12-08 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0015_budgetsettingsoverrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetsettingsoverrides',
            name='intervention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='snt_malaria.intervention'),
        ),
        migrations.AlterField(
            model_name='budgetsettingsoverrides',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario', to='snt_malaria.scenario'),
        ),
    ]
