# Generated by Django 4.2.27 on 2025-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0015_budgetassumptions"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DELETE FROM snt_malaria_budgetassumptions;",
            reverse_sql="",
        ),
        migrations.AlterUniqueTogether(
            name="budgetassumptions",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="budgetassumptions",
            name="intervention_code",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="budgetassumptions",
            unique_together={("scenario", "intervention_code")},
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="intervention",
        ),
    ]
