# Generated by Django 4.2.27 on 2026-01-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0017_intervention_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
