# Generated by Django 4.2.17 on 2026-01-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0018_scenario_is_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="SNTPermissionSupport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("iaso_snt_scenario_basic_write", "Scenario - Basic Write"),
                    ("iaso_snt_scenario_full_write", "Scenario - Full Write"),
                    ("iaso_snt_settings_read", "Settings - Read"),
                    ("iaso_snt_settings_write", "Settings - Write"),
                ],
                "managed": False,
                "default_permissions": [],
            },
        ),
    ]
