# Generated by Django 4.2.28 on 2026-02-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0019_sntpermissionsupport"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="population_input",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
    ]
