# Generated by Django 4.2.17 on 2026-02-17 16:07

import django.contrib.postgres.fields
import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models

import iaso.utils.models.color


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("snt_malaria", "0019_sntpermissionsupport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("priority", models.PositiveSmallIntegerField()),
                (
                    "color",
                    iaso.utils.models.color.ColorField(
                        default="#1976D2",
                        max_length=7,
                        validators=[iaso.utils.models.color.validate_hex_color],
                    ),
                ),
                ("matching_criteria", models.JSONField()),
                (
                    "org_units_matched",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "org_units_excluded",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "org_units_included",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "org_units_scope",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioRuleInterventionProperties",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coverage", models.DecimalField(decimal_places=2, max_digits=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="age_string",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="bale_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="buffer_mult",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="coverage",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="divisor",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="doses_per_child",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="doses_per_pw",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="monthly_rounds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="pop_prop_12_59",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="pop_prop_3_11",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="tablet_factor",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="touchpoints",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="interventionassignment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("coverage__isnull", True),
                        models.Q(("coverage__gte", 0), ("coverage__lte", 1)),
                        _connector="OR",
                    )
                ),
                name="assignment_coverage_between_0_and_1",
            ),
        ),
        migrations.AddField(
            model_name="scenarioruleinterventionproperties",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenario_rule_properties",
                to="snt_malaria.intervention",
            ),
        ),
        migrations.AddField(
            model_name="scenarioruleinterventionproperties",
            name="scenario_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervention_properties",
                to="snt_malaria.scenariorule",
            ),
        ),
        migrations.AddField(
            model_name="scenariorule",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_scenario_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scenariorule",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="snt_malaria.scenario",
            ),
        ),
        migrations.AddField(
            model_name="scenariorule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_scenario_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intervention_assignments",
                to="snt_malaria.scenariorule",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenarioruleinterventionproperties",
            constraint=models.UniqueConstraint(
                fields=("scenario_rule", "intervention"),
                name="scenario_rule_intervention_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenarioruleinterventionproperties",
            constraint=models.CheckConstraint(
                check=models.Q(("coverage__gte", 0), ("coverage__lte", 1)),
                name="intervention_properties_coverage_between_0_and_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariorule",
            constraint=models.UniqueConstraint(fields=("scenario", "priority"), name="scenario_rule_priority_unique"),
        ),
    ]
