# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snt_malaria", "0020_budget_population_input"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactProviderConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_key",
                    models.CharField(
                        choices=[("swisstph", "SwissTPH"), ("idm", "IDM")],
                        help_text="The impact data provider to use for this account.",
                        max_length=50,
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impact_provider_config",
                        to="iaso.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impact provider configuration",
                "verbose_name_plural": "Impact provider configurations",
            },
        ),
    ]
