# Generated by Django 4.2.17 on 2026-02-26 16:06

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0366_alter_profile_color_alter_project_color_and_more"),
        (
            "snt_malaria",
            "0021_scenariorule_scenarioruleinterventionproperties_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="interventionassignment",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="snt_malaria.intervention",
            ),
        ),
        migrations.AlterField(
            model_name="interventionassignment",
            name="org_unit",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.orgunit"),
        ),
        migrations.AlterField(
            model_name="interventionassignment",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervention_assignments",
                to="snt_malaria.scenariorule",
            ),
        ),
    ]
