# Generated by Django 4.2.17 on 2026-02-27 17:53

import django.db.models.constraints

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0022_alter_interventionassignment_intervention_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scenariorule",
            name="scenario_rule_priority_unique",
        ),
        migrations.AddConstraint(
            model_name="scenariorule",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["IMMEDIATE"],
                fields=("scenario", "priority"),
                name="scenario_rule_priority_unique",
            ),
        ),
    ]
