# Generated by Django 4.2.28 on 2026-03-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0021_impactproviderconfig'),
        ('snt_malaria', '0023_remove_scenariorule_scenario_rule_priority_unique_and_more'),
    ]

    operations = [
    ]
