# Generated by Django 4.2.17 on 2026-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "snt_malaria",
            "0023_remove_scenariorule_scenario_rule_priority_unique_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scenario",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("account", "name"),
                name="scenario_name_account_unique",
            ),
        ),
    ]
