# Generated by Django 4.2.17 on 2026-03-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0024_impactproviderconfig"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scenario",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("account", "name"),
                name="scenario_name_account_unique",
            ),
        ),
    ]
