# Generated by Django 4.2.29 on 2026-03-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0025_alter_scenario_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="impact_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reference used to match this intervention to its counterpart in the configured impact data source. The format depends on the provider: for SwissTPH, use the deployed_int_* column name (e.g. 'deployed_int_smc') or a comma-separated list for multiple columns (e.g. 'deployed_int_pbo,deployed_int_itn'); for IDM, use 'type:option' from the intervention_package table (e.g. 'smc:pmc').",
                max_length=100,
                verbose_name="Impact Provider Reference",
            ),
        ),
    ]
