# Generated by Django 4.2.29 on 2026-03-23 08:34

from django.db import migrations, models

import iaso.utils.models.encrypted_text_field


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0028_alter_impactproviderconfig_provider_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactproviderconfig",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific configuration (non-secret). For database providers: {db_name, db_host, db_port, db_username}.",
            ),
        ),
        migrations.AddField(
            model_name="impactproviderconfig",
            name="secret",
            field=iaso.utils.models.encrypted_text_field.EncryptedTextField(
                blank=True,
                help_text="Provider secret (password, token, API key). For database providers this is the database password.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="impactproviderconfig",
            name="provider_key",
            field=models.CharField(
                choices=[("swisstph", "SwissTPH"), ("idm", "IDM")],
                help_text="The impact data provider to use for this account.",
                max_length=50,
            ),
        ),
    ]
