# Generated by Django 4.2.29

from django.db import migrations, models

import iaso.utils.models.encrypted_text_field


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0028_alter_impactproviderconfig_provider_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactproviderconfig",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific configuration (non-secret). For database providers: {db_name, db_host, db_port, db_username}.",
            ),
        ),
        migrations.AddField(
            model_name="impactproviderconfig",
            name="secret",
            field=iaso.utils.models.encrypted_text_field.EncryptedTextField(
                blank=True,
                default="",
                help_text="Provider secret (password, token, API key). For database providers this is the database password.",
            ),
        ),
    ]
