# Generated by Django 4.2.29 on 2026-03-23 08:41

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0369_instance_parent_artefact_for_validation_and_more"),
        ("snt_malaria", "0029_impactproviderconfig_config_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactOrgUnitMapping",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reference",
                    models.CharField(
                        help_text="The reference string used to match this org unit in the external impact database.",
                        max_length=255,
                    ),
                ),
                (
                    "org_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="impact_mapping", to="iaso.orgunit"
                    ),
                ),
            ],
        ),
    ]
