# Generated by Django 4.2.29 on 2026-03-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0029_impactproviderconfig_config_and_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impactproviderconfig",
            name="provider_key",
            field=models.CharField(
                choices=[("swisstph", "SwissTPH"), ("idm", "IDM")],
                help_text="The impact data provider to use for this account.",
                max_length=50,
            ),
        ),
    ]
