# Generated by Django 4.2.17 on 2026-03-28 15:04

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import plugins.snt_malaria.models.snt_account_setup


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0372_auto_20260323_1438"),
        ("snt_malaria", "0030_impactorgunitmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="SNTAccountSetup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "French"), ("en", "English")],
                        default="en",
                        max_length=200,
                    ),
                ),
                (
                    "geo_json_file",
                    models.FileField(
                        upload_to=plugins.snt_malaria.models.snt_account_setup.account_setup_file_upload_to
                    ),
                ),
                (
                    "gpkg_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=plugins.snt_malaria.models.snt_account_setup.account_setup_file_upload_to,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snt_account_setup",
                        to="iaso.account",
                    ),
                ),
            ],
        ),
    ]
