# Generated by Django 4.2.30 on 2026-04-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0032_rename_and_add_org_unit_type_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventioncostbreakdownline',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdown_lines', to='snt_malaria.intervention'),
        ),
    ]
