# Generated by Django 4.2.30 on 2026-04-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0032_rename_and_add_org_unit_type_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactproviderconfig",
            name="cache_ttl_seconds",
            field=models.PositiveIntegerField(
                default=604800,
                help_text="How long impact API responses are cached, in seconds. Default is 7 days (604800).",
            ),
        ),
    ]
