# Generated by Django 4.2.30 on 2026-04-16 07:06

import django.contrib.postgres.fields
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0033_impactproviderconfig_cache_ttl_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="target_population",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="interventioncostbreakdownline",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_breakdown_lines",
                to="snt_malaria.intervention",
            ),
        ),
    ]
