# Generated by Django 4.2.30 on 2026-04-10 12:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0033_alter_interventioncostbreakdownline_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='target_population',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
