# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0034_intervention_target_population_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impactproviderconfig",
            name="provider_key",
            field=models.CharField(
                choices=[
                    ("swisstph", "SwissTPH"),
                    ("idm", "IDM"),
                    ("fake", "Fake (demo)"),
                ],
                help_text="The impact data provider to use for this account.",
                max_length=50,
            ),
        ),
    ]
