# Generated by Django 4.2.30 on 2026-04-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snt_malaria', '0034_intervention_target_population_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventioncostbreakdownline',
            name='year',
        ),
    ]
