# Generated by Django 4.2.30 on 2026-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0035_remove_interventioncostbreakdownline_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impactproviderconfig",
            name="provider_key",
            field=models.CharField(
                choices=[("swisstph", "SwissTPH"), ("idm", "IDM"), ("fake", "Fake (demo)")],
                help_text="The impact data provider to use for this account.",
                max_length=50,
            ),
        ),
    ]
