# Generated by Django 4.2.30 on 2026-04-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0037_sntaccountsetup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariorule",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
