# Generated by Django 4.2.30 on 2026-05-06 13:12

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0038_alter_scenariorule_name"),
    ]

    def remove_previous_assumptions(apps, schema_editor):
        BudgetAssumptions = apps.get_model("snt_malaria", "BudgetAssumptions")
        BudgetAssumptions.objects.all().delete()

    operations = [
        migrations.RunPython(remove_previous_assumptions),
        migrations.AlterUniqueTogether(
            name="budgetassumptions",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="budgetassumptions",
            name="intervention_assignment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_assumptions",
                to="snt_malaria.interventionassignment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetassumptions",
            name="year",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="budgetassumptions",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_assumptions_set",
                to="snt_malaria.scenario",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetassumptions",
            constraint=models.UniqueConstraint(
                fields=("scenario", "intervention_assignment", "year"),
                name="unique_budget_assumption_per_assignment_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetassumptions",
            constraint=models.CheckConstraint(
                check=models.Q(("coverage__gte", 0), ("coverage__lte", 1)),
                name="budget_assumptions_coverage_between_0_and_1",
            ),
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="age_string",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="bale_size",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="buffer_mult",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="divisor",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="doses_per_child",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="doses_per_pw",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="intervention_code",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="monthly_rounds",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="pop_prop_12_59",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="pop_prop_3_11",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="tablet_factor",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="touchpoints",
        ),
    ]
