# Generated by Django 4.2.30 on 2026-04-28 14:18

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0038_alter_scenariorule_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budgetassumptions",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="budgetassumptions",
            name="intervention_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_assumptions",
                to="snt_malaria.interventionassignment",
            ),
        ),
        migrations.AddField(
            model_name="budgetassumptions",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetassumptions",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_assumptions_set",
                to="snt_malaria.scenario",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetassumptions",
            constraint=models.UniqueConstraint(
                condition=models.Q(("intervention_assignment__isnull", False), ("year__isnull", False)),
                fields=("scenario", "intervention_assignment", "year"),
                name="unique_budget_assumption_per_assignment_year",
            ),
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="age_string",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="bale_size",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="buffer_mult",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="divisor",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="doses_per_child",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="doses_per_pw",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="intervention_code",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="monthly_rounds",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="pop_prop_12_59",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="pop_prop_3_11",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="tablet_factor",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="touchpoints",
        ),
    ]
