# Generated by Django 4.2.30 on 2026-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0042_scenarioyearlycostassignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervention",
            name="allowed_cost_unit_types",
        ),
        migrations.AlterField(
            model_name="interventioncostbreakdownline",
            name="cost_driver",
            field=models.CharField(
                choices=[("population", "Population"), ("fix_cost", "Fixed cost")], default="fix_cost", max_length=20
            ),
        ),
    ]
