# Generated by Django 4.2.30 on 2026-05-19 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0042_scenarioyearlycostassignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervention",
            name="allowed_cost_unit_types",
        )
    ]
