# Generated by Django 4.2.30 on 2026-06-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0044_set_cost_breakdown_population_layer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="costunittype",
            old_name="ratio",
            new_name="value",
        ),
        migrations.AddField(
            model_name="costunittype",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costunittype",
            name="invert_value",
            field=models.BooleanField(default=False),
        ),
    ]
