# Generated by Django 4.2.30 on 2026-06-08 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0045_rename_ratio_costunittype_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="intervention_assignment",
        ),
        migrations.RemoveField(
            model_name="budgetassumptions",
            name="scenario",
        ),
        migrations.RemoveConstraint(
            model_name="interventionassignment",
            name="assignment_coverage_between_0_and_1",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="age_string",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="bale_size",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="buffer_mult",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="coverage",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="divisor",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="doses_per_child",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="doses_per_pw",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="monthly_rounds",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="pop_prop_12_59",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="pop_prop_3_11",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="tablet_factor",
        ),
        migrations.RemoveField(
            model_name="interventionassignment",
            name="touchpoints",
        ),
        migrations.DeleteModel(
            name="BudgetAssumptions",
        ),
    ]
