# Generated by Django 4.2.30 on 2026-06-15 14:12

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0390_add_stock_management_feature_flag_category"),
        ("snt_malaria", "0046_remove_budgetassumptions_intervention_assignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="snt_donors", to="iaso.account"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="snt_grants", to="iaso.account"
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="grants", to="snt_malaria.donor"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="intervention",
            name="grant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventions",
                to="snt_malaria.grant",
            ),
        ),
        migrations.AddField(
            model_name="interventionassignment",
            name="grant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intervention_assignments",
                to="snt_malaria.grant",
            ),
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.UniqueConstraint(fields=("account", "name"), name="snt_malaria_grant_account_name_uniq"),
        ),
        migrations.AddConstraint(
            model_name="donor",
            constraint=models.UniqueConstraint(fields=("account", "name"), name="snt_malaria_donor_account_name_uniq"),
        ),
    ]
