# Generated by Django 4.2.30 on 2026-06-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0394_remove_show_pages_feature_flag'),
        ('snt_malaria', '0049_budgetsettings_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='default_population',
            field=models.ForeignKey(blank=True, help_text='Default population metric type used across the account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='iaso.metrictype'),
        ),
    ]
