# Generated by Django 4.2.30 on 2026-07-01 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0052_scenario_reference_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interventioncostbreakdownline",
            name="cost_driver",
        ),
    ]
