# Generated by Django 4.2.30 on 2026-07-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0055_move_conversion_to_cost_lines"),
    ]

    operations = [
        migrations.AddField(
            model_name="costunittype",
            name="is_commodity",
            field=models.BooleanField(default=False),
        ),
    ]
