# Generated by Django 4.2.30 on 2026-07-24 14:43

import django.db.models.deletion

from django.db import migrations, models


def copy_intervention_links_to_through_model(apps, schema_editor):
    ScenarioRule = apps.get_model("snt_malaria", "ScenarioRule")
    ScenarioRuleIntervention = apps.get_model("snt_malaria", "ScenarioRuleIntervention")

    old_through = ScenarioRule.interventions.through
    links = [
        ScenarioRuleIntervention(scenario_rule_id=row.scenariorule_id, intervention_id=row.intervention_id)
        for row in old_through.objects.all()
    ]
    ScenarioRuleIntervention.objects.bulk_create(links)


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0057_alter_intervention_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioRuleIntervention",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "intervention",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="snt_malaria.intervention"),
                ),
                (
                    "scenario_rule",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="snt_malaria.scenariorule"),
                ),
            ],
            options={
                "unique_together": {("scenario_rule", "intervention")},
            },
        ),
        migrations.RunPython(copy_intervention_links_to_through_model, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="scenariorule",
            name="interventions",
        ),
        migrations.AddField(
            model_name="scenariorule",
            name="interventions",
            field=models.ManyToManyField(
                blank=True,
                related_name="scenario_rules",
                through="snt_malaria.ScenarioRuleIntervention",
                to="snt_malaria.intervention",
            ),
        ),
    ]
