# Generated by Django 4.2.30 on 2026-07-30 13:54

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0395_oucr_geom_code"),
        ("snt_malaria", "0058_scenarioruleintervention_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositelayer",
            name="legend_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="compositelayer",
            name="legend_reference_metric_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="iaso.metrictype",
            ),
        ),
        migrations.AddField(
            model_name="compositelayer",
            name="legend_type",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("reference", "Reference"),
                    ("linear", "Linear"),
                    ("threshold", "Threshold"),
                    ("ordinal", "Ordinal"),
                ],
                default="auto",
                max_length=40,
            ),
        ),
    ]
