# Generated by Django 4.2.30 on 2026-08-03 08:44

from django.db import migrations, models


def backfill_data_layer_years_from_reference_year(apps, schema_editor):
    """Every metric type known to a scenario's account gets stamped with that
    scenario's old global reference_year, matching the pre-migration behavior
    where a single reference_year applied to all data layers."""
    Scenario = apps.get_model("snt_malaria", "Scenario")
    MetricType = apps.get_model("iaso", "MetricType")
    db_alias = schema_editor.connection.alias

    scenarios = list(Scenario.objects.using(db_alias).exclude(reference_year__isnull=True))
    if not scenarios:
        return

    metric_type_ids_by_account = {}
    to_update = []
    for scenario in scenarios:
        if scenario.account_id not in metric_type_ids_by_account:
            metric_type_ids_by_account[scenario.account_id] = list(
                MetricType.objects.using(db_alias).filter(account_id=scenario.account_id).values_list("id", flat=True)
            )
        metric_type_ids = metric_type_ids_by_account[scenario.account_id]
        scenario.data_layer_years = {str(metric_type_id): scenario.reference_year for metric_type_id in metric_type_ids}
        to_update.append(scenario)

    Scenario.objects.using(db_alias).bulk_update(to_update, ["data_layer_years"])


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0059_compositelayer_legend_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="data_layer_years",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(
            backfill_data_layer_years_from_reference_year,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="reference_year",
        ),
    ]
