# Generated by Django 4.2.30 on 2026-08-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0059_compositelayer_legend_config_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenario",
            name="reference_year",
        ),
        migrations.AddField(
            model_name="scenario",
            name="data_layer_years",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
