# Generated by Django 4.2.30 on 2026-09-29 11:56

from django.db import migrations, models

import iaso.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0061_metricvalue_year_zero_to_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariorule",
            name="matching_criteria",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[
                    iaso.utils.validators.JSONSchemaValidator(
                        schema={
                            "$defs": {
                                "condition": {
                                    "additionalProperties": False,
                                    "maxProperties": 1,
                                    "minProperties": 1,
                                    "patternProperties": {
                                        "^(==|<=|>=|<|>)$": {
                                            "items": [{"$ref": "#/$defs/varObject"}, {"$ref": "#/$defs/value"}],
                                            "maxItems": 2,
                                            "minItems": 2,
                                            "type": "array",
                                        }
                                    },
                                    "type": "object",
                                },
                                "value": {
                                    "anyOf": [
                                        {"minLength": 1, "type": "string"},
                                        {"type": "number"},
                                        {"type": "integer"},
                                        {"type": "boolean"},
                                    ]
                                },
                                "varObject": {
                                    "additionalProperties": False,
                                    "properties": {"var": {"type": "integer"}},
                                    "required": ["var"],
                                    "type": "object",
                                },
                            },
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "additionalProperties": False,
                            "properties": {
                                "and": {"items": {"$ref": "#/$defs/condition"}, "minItems": 1, "type": "array"}
                            },
                            "required": ["and"],
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
    ]
