# Generated by Django 4.2.30 on 2026-10-02 12:05

from decimal import Decimal

import django.core.validators

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0061_metricvalue_year_zero_to_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="interventioncostbreakdownline",
            name="coverage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
    ]
