# Generated by Django 4.2.30 on 2026-10-05 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0062_alter_intervention_impact_ref"),
        ("snt_malaria", "0062_alter_scenariorule_matching_criteria"),
    ]

    operations = []
