# Generated by Django 4.2.30 on 2026-10-05 12:06

from decimal import Decimal

import django.core.validators

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0062_interventioncostbreakdownline_coverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="interventioncostbreakdownline",
            name="buffer",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
