# Generated by Django 4.2.30 on 2026-10-05 14:51

from decimal import Decimal

import django.core.validators

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0063_merge_20261005_1343"),
    ]

    operations = [
        migrations.AddField(
            model_name="interventioncostbreakdownline",
            name="buffer",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="interventioncostbreakdownline",
            name="coverage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
    ]
