# Generated by Django 4.2.30 on 2026-10-08 11:09

from decimal import Decimal

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0064_interventioncostbreakdownline_buffer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenarioruleintervention",
            name="deployment_years",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="scenarioruleintervention",
            name="grant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scenario_rule_interventions",
                to="snt_malaria.grant",
            ),
        ),
        migrations.AlterField(
            model_name="interventioncostbreakdownline",
            name="coverage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100"),
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.CreateModel(
            name="ScenarioRuleCostOverride",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=19,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "buffer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "coverage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "cost_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_overrides",
                        to="snt_malaria.interventioncostbreakdownline",
                    ),
                ),
                (
                    "rule_intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_overrides",
                        to="snt_malaria.scenarioruleintervention",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="scenariorulecostoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("year__isnull", False)),
                fields=("rule_intervention", "cost_line", "year"),
                name="scenario_rule_cost_override_unique_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariorulecostoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("year__isnull", True)),
                fields=("rule_intervention", "cost_line"),
                name="scenario_rule_cost_override_unique_all_years",
            ),
        ),
    ]
