# Generated by Django 4.2.30 on 2026-10-08 11:09

from collections import defaultdict
from decimal import Decimal

from django.db import migrations


def yearly_coverages_from_legacy(is_proportional, legacy_values, start_year, end_year):
    """Converts a cost line's scenario yearly values into per-year coverage values.

    Proportional values are ratios of the population and become percentages. Fixed values are
    quantities that defaulted to 0 when unset, so every scenario year gets its quantity.
    """
    if is_proportional:
        return {
            year: min(value * Decimal("100"), Decimal("100"))
            for year, value in legacy_values.items()
            if start_year <= year <= end_year
        }
    return {year: legacy_values.get(year, Decimal("0")) for year in range(start_year, end_year + 1)}


def migrate_yearly_cost_assignments(apps, schema_editor):
    ScenarioYearlyCostAssignment = apps.get_model("snt_malaria", "ScenarioYearlyCostAssignment")
    ScenarioRuleIntervention = apps.get_model("snt_malaria", "ScenarioRuleIntervention")
    ScenarioRuleCostOverride = apps.get_model("snt_malaria", "ScenarioRuleCostOverride")
    InterventionCostBreakdownLine = apps.get_model("snt_malaria", "InterventionCostBreakdownLine")

    legacy_values = defaultdict(dict)
    for row in ScenarioYearlyCostAssignment.objects.values("scenario_id", "cost_line_id", "year", "value"):
        legacy_values[(row["scenario_id"], row["cost_line_id"])][row["year"]] = row["value"]

    lines_by_intervention = defaultdict(list)
    for line in InterventionCostBreakdownLine.objects.values("id", "intervention_id", "is_proportional"):
        lines_by_intervention[line["intervention_id"]].append(line)

    overrides = []
    rule_interventions = ScenarioRuleIntervention.objects.select_related("scenario_rule__scenario")
    for rule_intervention in rule_interventions.iterator():
        scenario = rule_intervention.scenario_rule.scenario
        for line in lines_by_intervention[rule_intervention.intervention_id]:
            coverages = yearly_coverages_from_legacy(
                line["is_proportional"],
                legacy_values.get((scenario.id, line["id"]), {}),
                scenario.start_year,
                scenario.end_year,
            )
            overrides.extend(
                ScenarioRuleCostOverride(
                    rule_intervention_id=rule_intervention.id, cost_line_id=line["id"], year=year, coverage=coverage
                )
                for year, coverage in coverages.items()
            )
    ScenarioRuleCostOverride.objects.bulk_create(overrides, batch_size=1000)


def set_fixed_line_quantities(apps, schema_editor):
    InterventionCostBreakdownLine = apps.get_model("snt_malaria", "InterventionCostBreakdownLine")
    InterventionCostBreakdownLine.objects.filter(is_proportional=False).update(coverage=Decimal("1"))


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0065_scenario_rule_cost_overrides"),
    ]

    operations = [
        migrations.RunPython(set_fixed_line_quantities, migrations.RunPython.noop),
        migrations.RunPython(migrate_yearly_cost_assignments, migrations.RunPython.noop),
    ]
