# Generated by Django 4.2.30 on 2026-10-08 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snt_malaria", "0066_migrate_yearly_cost_assignments_to_rule_overrides"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScenarioYearlyCostAssignment",
        ),
    ]
