import { ALL_YEARS_VALUE } from '../flumeConfig';
import { FlumeGraph, FlumeGraphNode, NODE_TYPES } from '../types/flumeGraph';

export const findOutputNode = (graph: FlumeGraph): FlumeGraphNode | undefined =>
    Object.values(graph ?? {}).find(node => node?.type === NODE_TYPES.output);

/** Whether the output node has anything wired into its `layer` input. */
export const isOutputConnected = (graph: FlumeGraph): boolean => {
    const sources = findOutputNode(graph)?.connections?.inputs?.layer;
    return Array.isArray(sources) && sources.length > 0;
};

/**
 * Return a copy of the graph with the connection into a given input port removed on both sides
 * (the target's `inputs[port]` and each source's matching `outputs[port]` entry). Backs the
 * drag-an-input-into-empty-space removal gesture (Flume's own port handling is unreliable here).
 */
export const removeInputConnection = (
    graph: FlumeGraph,
    inputNodeId: string,
    inputPortName: string,
): FlumeGraph => {
    const next: FlumeGraph = JSON.parse(JSON.stringify(graph ?? {}));
    const inputNode = next[inputNodeId];
    const sources = inputNode?.connections?.inputs?.[inputPortName];
    if (!inputNode || !sources?.length) return next;

    delete inputNode.connections.inputs[inputPortName];

    sources.forEach(source => {
        const sourceNode = next[source.nodeId];
        const outputs = sourceNode?.connections?.outputs?.[source.portName];
        if (!outputs) return;
        const remaining = outputs.filter(
            target =>
                !(
                    target.nodeId === inputNodeId &&
                    target.portName === inputPortName
                ),
        );
        if (remaining.length) {
            sourceNode.connections.outputs[source.portName] = remaining;
        } else {
            delete sourceNode.connections.outputs[source.portName];
        }
    });

    return next;
};

/**
 * MetricType ids of the data layers wired into the output node, in traversal order (deduped).
 *
 * Walks the graph depth-first from the output node following input connections, so it finds data
 * layers even when they sit behind formula/reclassify nodes. Mirrors the backend traversal in
 * `services/composite/evaluator.py` so the UI ordering matches the backend's default pick.
 */
export const getConnectedDataLayerIds = (graph: FlumeGraph): number[] => {
    const nodes = graph ?? {};
    const output = findOutputNode(nodes);
    if (!output) return [];

    const ordered: number[] = [];
    const visited = new Set<string>();

    const visit = (nodeId: string) => {
        if (visited.has(nodeId)) return;
        visited.add(nodeId);
        const node = nodes[nodeId];
        if (!node) return;
        if (node.type === NODE_TYPES.dataLayer) {
            const raw = node.inputData?.metricType?.metricTypeId;
            const id = raw === '' || raw == null ? undefined : Number(raw);
            if (
                id !== undefined &&
                !Number.isNaN(id) &&
                !ordered.includes(id)
            ) {
                ordered.push(id);
            }
        }
        const inputs = node.connections?.inputs ?? {};
        Object.values(inputs).forEach(sources => {
            (sources ?? []).forEach(source => visit(source.nodeId));
        });
    };

    visit(output.id);
    return ordered;
};

/**
 * MetricType ids picked on every `dataLayer` node in the graph, connected or not (deduped, order
 * not meaningful). Drives fetching the years available per layer, for the "Yearly values" control.
 */
export const getAllDataLayerMetricTypeIds = (graph: FlumeGraph): number[] => {
    const ids = new Set<number>();
    Object.values(graph ?? {}).forEach(node => {
        if (node?.type !== NODE_TYPES.dataLayer) return;
        const raw = node.inputData?.metricType?.metricTypeId;
        const id = raw === '' || raw == null ? undefined : Number(raw);
        if (id !== undefined && !Number.isNaN(id)) ids.add(id);
    });
    return [...ids];
};

/**
 * Backfills `selectedYear: "all"` onto every `dataLayer` node missing it, so the "Yearly values"
 * control always shows its real "Yearly" selection (with its helper text) instead of a bare
 * placeholder. Only genuinely new nodes added through Flume's own "add node" menu get this from
 * the control's `defaultValue` automatically — graphs loaded from the backend, generated by the
 * AI chat, or built by the canvas-drop handler bypass that and need it applied here instead.
 */
export const withDefaultSelectedYear = (
    graph?: FlumeGraph,
): FlumeGraph | undefined => {
    if (!graph) return graph;
    let changed = false;
    const next: FlumeGraph = { ...graph };
    Object.entries(graph).forEach(([nodeId, node]) => {
        if (node?.type !== NODE_TYPES.dataLayer) return;
        if (node.inputData?.metricType?.selectedYear !== undefined) return;
        changed = true;
        next[nodeId] = {
            ...node,
            inputData: {
                ...node.inputData,
                metricType: {
                    ...node.inputData?.metricType,
                    selectedYear: ALL_YEARS_VALUE,
                },
            },
        };
    });
    return changed ? next : graph;
};
