"""Generate CREATE TABLE IF NOT EXISTS SQL from the SwissTPHImpactData Django model.

Introspects the unmanaged SwissTPHImpactData model via Django's SchemaEditor
to produce a SQL file that the OpenHEXA pipeline can execute to create the
impact_data table.  This keeps the pipeline schema in sync with the ORM model.

Usage:
    python manage.py generate_swisstph_impact_schema
    python manage.py generate_swisstph_impact_schema --output /custom/path/schema.sql
"""

import re

from pathlib import Path

from django.core.management.base import BaseCommand
from django.db import connections


DEFAULT_OUTPUT = (
    Path(__file__).resolve().parent.parent.parent / "openhexa" / "load_swisstph_csv" / "impact_data_schema.sql"
)


class Command(BaseCommand):
    help = "Generate CREATE TABLE IF NOT EXISTS SQL for the SwissTPHImpactData model"

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            type=str,
            default=str(DEFAULT_OUTPUT),
            help=f"Output path for the SQL file (default: {DEFAULT_OUTPUT})",
        )

    def handle(self, *args, **options):
        from plugins.snt_malaria.models.swisstph_impact import SwissTPHImpactData

        connection = connections["default"]
        with connection.schema_editor(collect_sql=True) as editor:
            editor.create_model(SwissTPHImpactData)
            for index in SwissTPHImpactData._meta.indexes:
                editor.add_index(SwissTPHImpactData, index)

        statements = editor.collected_sql
        if not statements:
            self.stderr.write(self.style.ERROR("SchemaEditor produced no SQL."))
            return

        formatted = []
        for stmt in statements:
            line = str(stmt).rstrip(";")
            line = re.sub(r"CREATE TABLE\b", "CREATE TABLE IF NOT EXISTS", line)
            line = re.sub(r"CREATE INDEX\b", "CREATE INDEX IF NOT EXISTS", line)
            if line.lstrip().startswith("CREATE TABLE"):
                line = self._format_create_table(line)
            formatted.append(line)
        sql = ";\n".join(formatted) + ";\n"

        header = "-- Auto-generated by command: generate_impact_schema.py\n-- Do not edit manually.\n\n"

        output_path = Path(options["output"])
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(header + sql)

        self.stdout.write(self.style.SUCCESS(f"Schema written to {output_path}"))

    @staticmethod
    def _format_create_table(stmt: str) -> str:
        """Reformat a single CREATE TABLE statement: one column per line."""
        stmt = re.sub(r",\s*(?=\")", ",\n    ", stmt)
        stmt = stmt.replace('("', '(\n    "', 1)
        stmt = re.sub(r"\)\s*$", "\n)", stmt)
        return stmt
