name: SNT malaria - develop

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  config:
    uses: BLSQ/iaso-ci/.github/workflows/config.yml@IA-5227-decouple-ci-actions-into-dedicated-repo
    permissions:
      pull-requests: write
      contents: read
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      pr_title: ${{ github.event.pull_request.title }}
      plugin_name: snt_malaria


  build_and_push_image:
    needs: config
    uses: BLSQ/iaso-ci/.github/workflows/docker_build.yml@IA-5227-decouple-ci-actions-into-dedicated-repo
    with:
      iaso_branch: ${{ needs.config.outputs.iaso_branch }}
      image_tags: ${{ needs.config.outputs.image_tags }}
      plugin_branch: ${{ needs.config.outputs.plugin_branch }}
      plugin_name: snt_malaria
    secrets: inherit

  tests:
    needs: config
    uses: BLSQ/iaso-ci/.github/workflows/tests.yml@IA-5227-decouple-ci-actions-into-dedicated-repo
    with:
      iaso_branch: ${{ needs.config.outputs.iaso_branch }}
      plugin_branch: ${{ needs.config.outputs.plugin_branch }}
      plugin_name: snt_malaria

  deploy_on_staging:
    needs: [ build_and_push_image, tests ]
    uses: BLSQ/iaso-ci/.github/workflows/docker_deploy.yml@IA-5227-decouple-ci-actions-into-dedicated-repo
    with:
      iaso_branch: develop
      plugin_branch: develop
      environment: snt-malaria-staging
      image_tag: develop
      plugin_name: snt_malaria
    secrets: inherit
