-- IDM database schema for the load_idm_data OpenHEXA pipeline.
--
-- This file is a hand-maintained replication of the setup scripts shipped
-- with IDM's MalariaInterventionPrioritizationDash repository (under
-- `db/init_sql/`): the same DDL and the same seed rows for the static
-- reference tables, flattened into one file that the pipeline can execute
-- verbatim against the workspace database.
--
-- Because it's a copy, it drifts when IDM changes their upstream scripts.
-- When that happens, update this file and the matching Django models in
-- plugins/snt_malaria/models/idm_impact.py together.
--
-- The pipeline runs this file at the start of every run to drop and
-- recreate the IDM tables, then seeds the static reference rows at the end.


-- =============================================================================
-- DROP (reverse dependency order)
-- =============================================================================

DROP TABLE IF EXISTS model_output CASCADE;
DROP TABLE IF EXISTS admin_info CASCADE;
DROP TABLE IF EXISTS age_group CASCADE;
DROP TABLE IF EXISTS coverage CASCADE;
DROP TABLE IF EXISTS intervention_package CASCADE;


-- =============================================================================
-- Reference tables
-- =============================================================================

CREATE TABLE admin_info (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_2_name varchar(255),
    state varchar(255),
    population integer,
    population_u5 integer
);

CREATE TABLE age_group (
    id integer PRIMARY KEY,
    option varchar(255)
);

CREATE TABLE coverage (
    id integer PRIMARY KEY,
    option varchar(255),
    key varchar(255),
    description varchar(255)
);

CREATE TABLE intervention_package (
    id integer PRIMARY KEY,
    option varchar(255),
    type varchar(255),
    description varchar(255)
);


-- =============================================================================
-- Simulation output (partitioned by admin_info range, matching IDM upstream)
-- =============================================================================
--
-- Postgres requires the partition key to be part of any PK on the parent. To
-- stay compatible with the non-composite PK on `id` that our ORM expects, we
-- leave the parent without a PK and attach PRIMARY KEY (id) to each partition.
-- The shared IDENTITY sequence on id keeps ids unique across partitions.

CREATE TABLE model_output (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    admin_info integer,
    year smallint,
    age_group integer,
    cm integer,
    cm_subsidy integer,
    smc integer,
    itn_c integer,
    itn_r integer,
    irs integer,
    vacc integer,
    iptp integer,
    lsm integer,
    cm_coverage integer,
    cm_subsidy_coverage integer,
    smc_coverage integer,
    itn_c_coverage integer,
    itn_r_coverage integer,
    irs_coverage integer,
    vacc_coverage integer,
    iptp_coverage integer,
    lsm_coverage integer,
    clinical_incidence numeric(20, 10),
    clinical_incidence_lower numeric(20, 10),
    clinical_incidence_higher numeric(20, 10),
    severe_incidence numeric(20, 10),
    severe_incidence_lower numeric(20, 10),
    severe_incidence_higher numeric(20, 10),
    prevalence numeric(20, 10),
    prevalence_lower numeric(20, 10),
    prevalence_higher numeric(20, 10),
    CONSTRAINT model_output_admin_info_fkey FOREIGN KEY (admin_info) REFERENCES admin_info (id),
    CONSTRAINT model_output_age_group_fkey FOREIGN KEY (age_group) REFERENCES age_group (id),
    CONSTRAINT model_output_cm_fkey FOREIGN KEY (cm) REFERENCES intervention_package (id),
    CONSTRAINT model_output_cm_subsidy_fkey FOREIGN KEY (cm_subsidy) REFERENCES intervention_package (id),
    CONSTRAINT model_output_smc_fkey FOREIGN KEY (smc) REFERENCES intervention_package (id),
    CONSTRAINT model_output_itn_c_fkey FOREIGN KEY (itn_c) REFERENCES intervention_package (id),
    CONSTRAINT model_output_itn_r_fkey FOREIGN KEY (itn_r) REFERENCES intervention_package (id),
    CONSTRAINT model_output_irs_fkey FOREIGN KEY (irs) REFERENCES intervention_package (id),
    CONSTRAINT model_output_vacc_fkey FOREIGN KEY (vacc) REFERENCES intervention_package (id),
    CONSTRAINT model_output_iptp_fkey FOREIGN KEY (iptp) REFERENCES intervention_package (id),
    CONSTRAINT model_output_lsm_fkey FOREIGN KEY (lsm) REFERENCES intervention_package (id),
    CONSTRAINT model_output_cm_coverage_fkey FOREIGN KEY (cm_coverage) REFERENCES coverage (id),
    CONSTRAINT model_output_cm_subsidy_coverage_fkey FOREIGN KEY (cm_subsidy_coverage) REFERENCES coverage (id),
    CONSTRAINT model_output_smc_coverage_fkey FOREIGN KEY (smc_coverage) REFERENCES coverage (id),
    CONSTRAINT model_output_itn_c_coverage_fkey FOREIGN KEY (itn_c_coverage) REFERENCES coverage (id),
    CONSTRAINT model_output_itn_r_coverage_fkey FOREIGN KEY (itn_r_coverage) REFERENCES coverage (id),
    CONSTRAINT model_output_irs_coverage_fkey FOREIGN KEY (irs_coverage) REFERENCES coverage (id),
    CONSTRAINT model_output_vacc_coverage_fkey FOREIGN KEY (vacc_coverage) REFERENCES coverage (id),
    CONSTRAINT model_output_iptp_coverage_fkey FOREIGN KEY (iptp_coverage) REFERENCES coverage (id),
    CONSTRAINT model_output_lsm_coverage_fkey FOREIGN KEY (lsm_coverage) REFERENCES coverage (id)
) PARTITION BY RANGE (admin_info);

CREATE TABLE model_output_200 PARTITION OF model_output
    (CONSTRAINT model_output_200_pkey PRIMARY KEY (id))
    FOR VALUES FROM (1) TO (200);

CREATE TABLE model_output_400 PARTITION OF model_output
    (CONSTRAINT model_output_400_pkey PRIMARY KEY (id))
    FOR VALUES FROM (200) TO (400);

CREATE TABLE model_output_600 PARTITION OF model_output
    (CONSTRAINT model_output_600_pkey PRIMARY KEY (id))
    FOR VALUES FROM (400) TO (600);

CREATE TABLE model_output_max PARTITION OF model_output
    (CONSTRAINT model_output_max_pkey PRIMARY KEY (id))
    FOR VALUES FROM (600) TO (MAXVALUE);


-- =============================================================================
-- Composite indexes on model_output (propagated to partitions)
-- =============================================================================

CREATE INDEX model_output_admin_info_idx
    ON model_output (admin_info);

CREATE INDEX model_output_intervention_idx
    ON model_output (cm, cm_subsidy, smc, itn_c, itn_r, irs, vacc, iptp, lsm);

CREATE INDEX model_output_coverage_idx
    ON model_output (cm_coverage, cm_subsidy_coverage, smc_coverage, itn_c_coverage, itn_r_coverage, irs_coverage, vacc_coverage, iptp_coverage, lsm_coverage);


-- =============================================================================
-- Static reference data
-- =============================================================================

INSERT INTO age_group (id, option) VALUES
    (1, 'under5'),
    (2, 'allAges');

INSERT INTO coverage (id, option, key, description) VALUES
    (1, 'current', 'current', 'estimated current coverage based on recent implementation in each LGA'),
    (2, '70%', '70', 'idealized effective coverage of 70%'),
    (3, 'Estimate 1 (≤25%)', 'estimate_1_current', '25% or less eligible children receiving the full 3-dose primary series'),
    (4, 'Estimate 2 (≤50%)', 'estimate_2_current', '50% or less eligible children receiving the full 3-dose primary series');

INSERT INTO intervention_package (id, option, type, description) VALUES
    (1, 'none', 'none', 'No ITN, no vaccine'),
    (2, 'cm', 'cm', 'Community Case Management'),
    (3, 'cm_subsidy', 'cm_subsidy', 'Community Case Management with Subsidy'),
    (4, 'smc', 'smc', 'SMC or PMC'),
    (5, 'pmc', 'smc', 'SMC or PMC'),
    (6, 'itn_c', 'itn_c', 'ITN Campaign'),
    (7, 'itn_r', 'itn_r', 'ITN Routine'),
    (8, 'irs', 'irs', 'Indoor Residual Spraying'),
    (9, 'vacc', 'vacc', 'RTSS like vaccine given through EPI with one booster'),
    (10, 'iptp', 'iptp', 'Intermittent Preventive Treatment in Pregnancy'),
    (11, 'lsm', 'lsm', 'Larval Source Management');
